/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualizar;


import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelos.Digitadores;
import modelos.banco.DigitadoresBanco;

/**
 *
 * @author renan
 */
public class TelaLogin extends javax.swing.JFrame {

    private int contadorLogAdmin = 0;
    private int contadorLogDigit = 0;

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        jAdminLogin.setVisible(false);
        jAdminSenha.setVisible(false);
        jTxtLogin.setVisible(false);
        jTxtSenha.setVisible(false);
        jAdminEntrar.setVisible(false);
        jAdminMenu.setForeground(Color.red);
        jEsqueceuSenhaAdmin.setVisible(false);

        procurarAdmin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTxtLogin = new javax.swing.JLabel();
        jAdminLogin = new javax.swing.JTextField();
        jTxtSenha = new javax.swing.JLabel();
        jAdminSenha = new javax.swing.JPasswordField();
        jAdminEntrar = new javax.swing.JButton();
        jEsqueceuSenhaAdmin = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jdNomeLogin = new javax.swing.JLabel();
        jDigitLogin = new javax.swing.JTextField();
        jdNomeSenha = new javax.swing.JLabel();
        jDigitSenha = new javax.swing.JPasswordField();
        jDigitEntrar = new javax.swing.JButton();
        jEsqueceuSenhaDigit = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jAdminMenu = new javax.swing.JMenu();
        jDigitMenu = new javax.swing.JMenu();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SCOH - Login");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons-hosp.png")).getImage());
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Admin"));

        jTxtLogin.setText("Login");
        jTxtLogin.setFocusTraversalPolicyProvider(true);

        jAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdminLoginActionPerformed(evt);
            }
        });
        jAdminLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jAdminLoginKeyPressed(evt);
            }
        });

        jTxtSenha.setText("Senha");

        jAdminSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jAdminSenhaKeyPressed(evt);
            }
        });

        jAdminEntrar.setText("Entrar");
        jAdminEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdminEntrarActionPerformed(evt);
            }
        });

        jEsqueceuSenhaAdmin.setBackground(new java.awt.Color(255, 255, 153));
        jEsqueceuSenhaAdmin.setText("Esqueceu sua senha?");
        jEsqueceuSenhaAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEsqueceuSenhaAdminActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/scohp3.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jEsqueceuSenhaAdmin))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1)
                        .addGap(0, 105, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTxtSenha)
                        .addComponent(jTxtLogin)
                        .addComponent(jAdminSenha)
                        .addComponent(jAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jAdminEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTxtLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jTxtSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAdminSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jAdminEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jEsqueceuSenhaAdmin))
        );

        jPanel1.add(jPanel2, "admin");

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Digitadores"));

        jdNomeLogin.setText("Login");

        jDigitLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDigitLoginKeyPressed(evt);
            }
        });

        jdNomeSenha.setText("Senha");

        jDigitSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDigitSenhaKeyPressed(evt);
            }
        });

        jDigitEntrar.setText("Entrar");
        jDigitEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDigitEntrarActionPerformed(evt);
            }
        });

        jEsqueceuSenhaDigit.setBackground(new java.awt.Color(204, 204, 255));
        jEsqueceuSenhaDigit.setText("Esqueceu sua senha?");
        jEsqueceuSenhaDigit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEsqueceuSenhaDigitActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/scohp3.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jEsqueceuSenhaDigit))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2)
                        .addGap(0, 108, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdNomeSenha)
                    .addComponent(jDigitSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jDigitEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdNomeLogin)
                            .addComponent(jDigitLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jdNomeLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDigitLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jdNomeSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDigitSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jDigitEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jEsqueceuSenhaDigit))
        );

        jPanel1.add(jPanel3, "digitadores");

        jAdminMenu.setBackground(new java.awt.Color(0, 0, 0));
        jAdminMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-macho-de-configurações-de-admin-16_2.png"))); // NOI18N
        jAdminMenu.setText("Admin");
        jAdminMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAdminMenuMouseClicked(evt);
            }
        });
        jAdminMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdminMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(jAdminMenu);

        jDigitMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-grupo-de-fundo-selecionado-16.png"))); // NOI18N
        jDigitMenu.setText("Digitadores");
        jDigitMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDigitMenuMouseClicked(evt);
            }
        });
        jDigitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDigitMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(jDigitMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jAdminMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdminMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAdminMenuActionPerformed

    private void jAdminMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAdminMenuMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "admin");
        jAdminMenu.setForeground(Color.red);
        jDigitMenu.setForeground(Color.black);
    }//GEN-LAST:event_jAdminMenuMouseClicked

    private void jDigitMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDigitMenuMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "digitadores");
        jDigitMenu.setForeground(Color.red);
        jAdminMenu.setForeground(Color.black);
    }//GEN-LAST:event_jDigitMenuMouseClicked

    /**
     * Valida a conta informada do Admin ou Digitador
     *
     * @param nome
     */
    private void entrarComSenha(boolean dig) {
        Digitadores digi = new Digitadores();
        digi.setNome("");  //Nome dado para que o admin não entre na outra área
        DigitadoresBanco db = new DigitadoresBanco();

        boolean check = false;
        if (dig) {
            //Verifica se é o Admin
            digi.setLogin(jAdminLogin.getText());
            digi.setSenha(new String(jAdminSenha.getPassword()));  // uso da classe Wrapper
        } else {

            digi.setLogin(jDigitLogin.getText());
            digi.setSenha(new String(jDigitSenha.getPassword()));
        }
        if (digi.getLogin().equals("admin") && digi.getSenha().equals("")) {
            check = true;               //verifica se é o primeiro login com o admin criado
        }

        if (db.validarConta(digi, dig)) {

            JOptionPane.showMessageDialog(this, "Bem vindo " + db.getDigiUsoNome(), "Bem Vindo",
                    JOptionPane.PLAIN_MESSAGE);
            new TelaInicial(db.getDigiUsoId(), check).setVisible(true);
            this.dispose();
        } else {
            if (dig) {
                JOptionPane.showMessageDialog(this, "Login ou Senha incorretos.", "Erro", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Login ou Senha incorretos.Tente novamente.\n\nVerifique com seu Admin se "
                        + "a sua conta foi cadastrada.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * Procura no banco se já existe um Admin
     */
    private void procurarAdmin() {
        Digitadores digi = new Digitadores(); //criando admin
        digi.setNome("Admin");
        DigitadoresBanco db = new DigitadoresBanco();

        if (db.verificarAdmin(digi)) {  // Procura se há admin caso n cria
            jAdminLogin.setVisible(true);
            jAdminSenha.setVisible(true);
            jTxtLogin.setVisible(true);
            jTxtSenha.setVisible(true);
            jAdminEntrar.setVisible(true);
            jEsqueceuSenhaAdmin.setVisible(true);
            jEsqueceuSenhaAdmin.setEnabled(false);
            jEsqueceuSenhaDigit.setEnabled(false);
        } else {
            jDigitMenu.setVisible(false);
            jAdminEntrar.setVisible(true);
            jAdminEntrar.setText("Criar");
        }
    }
    
      /**
     * Tenta contar a quantidade de caracteres em um determinado campo
     *
     * @param jCampo
     * @param contador
     * @param evt
     * @param keyEvent
     * @return
     */
    public static int contadorTexto(String jCampo, int contador, int evt, int keyEvent) {
        if (jCampo.length() == 0 || evt == keyEvent) {
            contador = jCampo.length();
            if (evt == keyEvent && contador > 0) {
                contador--;
            }
        } else {
            contador = jCampo.length() + 1; // in progress
        }
        return contador;
    }
    
    private void jAdminEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdminEntrarActionPerformed
        // TODO add your handling code here:
        if (jAdminLogin.isVisible()) {
            entrarComSenha(true);
        } else {                //Botão Criar
            Digitadores digi = new Digitadores("Admin", "0000-00-00", "", "", "", "", ""); //criando admin;
            DigitadoresBanco db = new DigitadoresBanco();

            if (db.inserir(digi)) {
                JOptionPane.showMessageDialog(this, "Bem vindo\nSua conta foi criada - Login: admin Senha:\n\nInsira "
                        + "estes dados para realizar a sua sessão.");
                procurarAdmin();

            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar o Admin. Tente novamente.", "Erro",
                        JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_jAdminEntrarActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
    }//GEN-LAST:event_formMouseMoved

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jAdminSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAdminSenhaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {    //Ao apertar Enter também é possível fazer login
            entrarComSenha(true);
        }
    }//GEN-LAST:event_jAdminSenhaKeyPressed

    private void jDigitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDigitMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDigitMenuActionPerformed

    private void jDigitEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDigitEntrarActionPerformed
        // TODO add your handling code here:
        entrarComSenha(false);  //false pois não é o admin
    }//GEN-LAST:event_jDigitEntrarActionPerformed

    private void jDigitSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDigitSenhaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            entrarComSenha(false);
        }
    }//GEN-LAST:event_jDigitSenhaKeyPressed

    private void jEsqueceuSenhaAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEsqueceuSenhaAdminActionPerformed
        // TODO add your handling code here:
        DigitadoresBanco db = new DigitadoresBanco();
        String userIdNome = db.buscaNomeId(jAdminLogin.getText());
        String userNome = userIdNome.substring(userIdNome.indexOf("/") + 1, userIdNome.length());
        int userId = Integer.parseInt(userIdNome.substring(0, userIdNome.indexOf("/")));    //Wrapp Int

        if (userId != -1 && userNome.equals("Admin")) {     // verifica se o login existe e se é o admin
            new TelaAtualizarAdmin(userId, true).setVisible(true);
            jEsqueceuSenhaAdmin.setSelected(false);
        } else {
            if (userId == -1) {
                JOptionPane.showMessageDialog(this, "O Login não existe. Tente novamente.", "Erro", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Faça Login na aba Digitadores.", "Erro", JOptionPane.ERROR_MESSAGE);

            }
            jEsqueceuSenhaAdmin.setSelected(false);
        }
    }//GEN-LAST:event_jEsqueceuSenhaAdminActionPerformed

    private void jEsqueceuSenhaDigitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEsqueceuSenhaDigitActionPerformed
        // TODO add your handling code here:
        DigitadoresBanco db = new DigitadoresBanco();
        String userIdNome = db.buscaNomeId(jDigitLogin.getText());
        String userNome = userIdNome.substring(userIdNome.indexOf("/") + 1, userIdNome.length());
        int userId = Integer.parseInt(userIdNome.substring(0, userIdNome.indexOf("/")));

        if (userId != -1 && !"Admin".equals(userNome)) {    // verifica se o login existe e se não é o admin
            new TelaAtualizarAdmin(userId, true).setVisible(true);
            jEsqueceuSenhaDigit.setSelected(false);
        } else {
            if (userId == -1) {
                JOptionPane.showMessageDialog(this, "O Login não existe. Tente novamente.", "Erro", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Faça Login na aba Admin.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            jEsqueceuSenhaDigit.setSelected(false);
        }
    }//GEN-LAST:event_jEsqueceuSenhaDigitActionPerformed

    private void jDigitLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDigitLoginKeyPressed
        // TODO add your handling code here:
        //Faz o botão Esqueceu Senha ficar habilitado ou desabilitado
        contadorLogDigit = contadorTexto(jDigitLogin.getText(), contadorLogDigit, evt.getKeyCode(), KeyEvent.VK_BACK_SPACE);
        
        if (!"".equals(jDigitLogin.getText()) && contadorLogDigit >= 5 && contadorLogDigit <= 15) {
            jEsqueceuSenhaDigit.setEnabled(true);
        } else {
            jEsqueceuSenhaDigit.setEnabled(false);
        }
    }//GEN-LAST:event_jDigitLoginKeyPressed

    private void jAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdminLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAdminLoginActionPerformed

    private void jAdminLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAdminLoginKeyPressed
        // TODO add your handling code here:
        contadorLogAdmin = contadorTexto(jAdminLogin.getText(), contadorLogAdmin, evt.getKeyCode(), KeyEvent.VK_BACK_SPACE);
        
        if (!"".equals(jAdminLogin.getText()) && contadorLogAdmin >= 5 && contadorLogAdmin <= 15) {
            jEsqueceuSenhaAdmin.setEnabled(true);
        } else {
            jEsqueceuSenhaAdmin.setEnabled(false);
        }
    }//GEN-LAST:event_jAdminLoginKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAdminEntrar;
    private javax.swing.JTextField jAdminLogin;
    private javax.swing.JMenu jAdminMenu;
    private javax.swing.JPasswordField jAdminSenha;
    private javax.swing.JButton jDigitEntrar;
    private javax.swing.JTextField jDigitLogin;
    private javax.swing.JMenu jDigitMenu;
    private javax.swing.JPasswordField jDigitSenha;
    private javax.swing.JRadioButton jEsqueceuSenhaAdmin;
    private javax.swing.JRadioButton jEsqueceuSenhaDigit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jTxtLogin;
    private javax.swing.JLabel jTxtSenha;
    private javax.swing.JLabel jdNomeLogin;
    private javax.swing.JLabel jdNomeSenha;
    // End of variables declaration//GEN-END:variables
}
