/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualizar;

import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;
import modelos.Digitadores;
import modelos.banco.DigitadoresBanco;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;
import javax.swing.JCheckBox;
import javax.swing.JPanel;

/**
 *
 * @author renan
 */
public class TelaDigitCadastrar extends javax.swing.JInternalFrame {

    private Digitadores digitador;
    private int idDigit;

    /**
     * Creates new form TelaUserInfo
     */
    public TelaDigitCadastrar() {
        initComponents();

        jAtualizar.setVisible(false);
        jPin.setVisible(false);
        jNomePin.setVisible(false);
    }

    public TelaDigitCadastrar(Digitadores digi) {
        initComponents();
        this.digitador = digi;
        idDigit = digi.getId();

        setTitle("Seus Dados: " + digi.getNome());

        jAtualizar.setVisible(false);
        jPin.setVisible(false);
        jNomePin.setVisible(false);

        jNome.setText(digi.getNome());
        jNascimento.setText(digi.getNascimento());

        if (digi.getSexo().equals("M")) {
            jSexoM.setSelected(true);
        } else if (digi.getSexo().equals("F")) {
            jSexoF.setSelected(true);
        }
        jContato.setText(digi.getContato());
        jRg.setText(digi.getRg());
        jCpf.setText(digi.getCpf());
        jEndereco.setText(digi.getEndereco());

        jNome.setEnabled(false);
        jNascimento.setEnabled(false);
        jSexoM.setEnabled(false);
        jSexoF.setEnabled(false);
        jContato.setEnabled(false);
        jRg.setEnabled(false);
        jCpf.setEnabled(false);
        jEndereco.setEnabled(false);

        jCadastrar.setText("Editar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jNome = new javax.swing.JTextField();
        jNascimento = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jSexoM = new javax.swing.JCheckBox();
        jSexoF = new javax.swing.JCheckBox();
        jContato = new javax.swing.JFormattedTextField();
        jCadastrar = new javax.swing.JButton();
        jAtualizar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCpf = new javax.swing.JFormattedTextField();
        jEndereco = new javax.swing.JTextField();
        jRg = new javax.swing.JTextField();
        jNomePin = new javax.swing.JLabel();
        jPin = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cadastrar Digitador");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Digitador"));

        jLabel1.setText("Nome*");

        jLabel2.setText("Nascimento*");

        jLabel3.setText("Contato");

        try {
            jNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jNascimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNascimentoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jNascimentoKeyReleased(evt);
            }
        });

        jLabel4.setText("Sexo*");

        jSexoM.setText("M");
        jSexoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSexoMActionPerformed(evt);
            }
        });

        jSexoF.setText("F");
        jSexoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSexoFActionPerformed(evt);
            }
        });

        try {
            jContato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jContato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jContatoKeyPressed(evt);
            }
        });

        jCadastrar.setText("Cadastrar");
        jCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastrarActionPerformed(evt);
            }
        });

        jAtualizar.setText("Atualizar");
        jAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAtualizarActionPerformed(evt);
            }
        });

        jLabel9.setText("RG*");

        jLabel10.setText("CPF*");

        jLabel11.setText("Endereço");

        try {
            jCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCpfKeyPressed(evt);
            }
        });

        jNomePin.setText("PIN*");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNomePin)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9)
                            .addComponent(jRg, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPin, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                    .addGap(40, 40, 40)
                                                    .addComponent(jLabel4)
                                                    .addGap(55, 55, 55)
                                                    .addComponent(jLabel3)
                                                    .addGap(109, 109, 109))
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                    .addGap(41, 41, 41)
                                                    .addComponent(jSexoM)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jSexoF)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jContato, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jAtualizar)
                                                .addGap(46, 46, 46)
                                                .addComponent(jCadastrar)
                                                .addGap(18, 18, 18))))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addComponent(jLabel11))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jEndereco)))))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSexoM)
                    .addComponent(jSexoF)
                    .addComponent(jContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jNomePin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAtualizar)
                    .addComponent(jCadastrar)
                    .addComponent(jPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSexoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSexoMActionPerformed
        // TODO add your handling code here:
        if (jSexoF.isSelected()) {
            jSexoF.setSelected(false);
        }
    }//GEN-LAST:event_jSexoMActionPerformed

    private void jSexoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSexoFActionPerformed
        // TODO add your handling code here:
        if (jSexoM.isSelected()) {
            jSexoM.setSelected(false);
        }
    }//GEN-LAST:event_jSexoFActionPerformed

    /**
     * Pega os dados da ficha (id, nome, nascimento, sexo, contato, cpf, rg,
     * endereço) e coloca formatado, pro banco, em um objeto Digitadores
     *
     * @param id
     * @param jNome
     * @param jNascimento
     * @param jSexoM
     * @param jContato
     * @param jRg
     * @param jCpf
     * @param jEndereco
     * @return
     */
    public static Digitadores getFormatedDigitadores(int id, JTextField jNome, JFormattedTextField jNascimento, JCheckBox jSexoM,
            JFormattedTextField jContato, JTextField jRg, JFormattedTextField jCpf, JTextField jEndereco) {
        Digitadores digi = new Digitadores();
        String newNasc = jNascimento.getText();
        String newCpf = jCpf.getText();
        String newContato = jContato.getText();

        digi.setNome(jNome.getText().trim());
        digi.setNascimento(newNasc.substring(6, 10) + "-" + newNasc.substring(3, 5) + "-" + newNasc.substring(0, 2));   // modificar a data para o formato do banco

        digi.setSexo(jSexoM.isSelected() ? "M" : "F");

        digi.setContato(newContato.substring(1, 3) + newContato.substring(5, 10) + newContato.substring(11, 15));   // retirar a formatação da máscara pro banco
        digi.setRg(jRg.getText());
        digi.setCpf(newCpf.substring(0, 3) + newCpf.substring(4, 7) + newCpf.substring(8, 11) + newCpf.substring(12, 14));
        digi.setEndereco(jEndereco.getText().trim());
        digi.setId(id);
        return digi;
    }

    /**
     * Verifica se tudo que foi digitado nas caixas de texto está nos conformes
     * do banco
     *
     * @param painel
     * @param jNome
     * @param jNascimento
     * @param jSexoM
     * @param jSexoF
     * @param jRg
     * @param jCpf
     * @param jEndereco
     * @return
     */
    public static boolean checkCaixas(JPanel painel, JTextField jNome, JFormattedTextField jNascimento, JCheckBox jSexoM, JCheckBox jSexoF,
            JTextField jRg, JFormattedTextField jCpf, JTextField jEndereco) {
        String rg = jRg.getText().trim();
        String txtnome = jNome.getText().trim();
        String endereco = jEndereco.getText().trim();

        if (txtnome.equals("")) {
            JOptionPane.showMessageDialog(painel, "O Nome do paciente deve ser preenchido.", "Aviso",
                    JOptionPane.WARNING_MESSAGE);
        } else if (txtnome.matches("\\D+") == false) {     //verificar se o txtnome é somente letras
            JOptionPane.showMessageDialog(painel, "O campo Nome não pode conter números ou símbolo.", "Erro",
                    JOptionPane.ERROR_MESSAGE);
        } else if (txtnome.equals("Admin")) {
            JOptionPane.showMessageDialog(painel, "O campo Nome não pode ser este", "Erro",
                    JOptionPane.ERROR_MESSAGE);
        } else if (txtnome.length() > 45) {
            JOptionPane.showMessageDialog(painel, "O Nome do digitador não pode conter muitos caracteres.", "Erro",
                    JOptionPane.ERROR_MESSAGE);
        } else if (jNascimento.getText().equals("  /  /    ")) {
            JOptionPane.showMessageDialog(painel, "A data de Nascimento do digitador deve ser preenchida.", "Aviso",
                    JOptionPane.WARNING_MESSAGE);
        } else if (jSexoM.isSelected() == false && jSexoF.isSelected() == false) {
            JOptionPane.showMessageDialog(painel, "É necessário informar o Sexo do digitador.", "Aviso",
                    JOptionPane.WARNING_MESSAGE);
        } else if (rg.equals("")) {
            JOptionPane.showMessageDialog(painel, "O RG do digitador deve ser preenchido.", "Aviso",
                    JOptionPane.WARNING_MESSAGE);
        } else if (rg.length() > 13) {
            JOptionPane.showMessageDialog(painel, "O RG do digitador deve conter no máximo 13 números.", "Aviso",
                    JOptionPane.WARNING_MESSAGE);
        } else if (rg.matches("\\d+") == false) {   //verifica se o rg é somente números
            JOptionPane.showMessageDialog(painel, "O campo RG só pode conter números.", "Erro",
                    JOptionPane.ERROR_MESSAGE);
        } else if (jCpf.getText().equals("   .   .   -  ")) {
            JOptionPane.showMessageDialog(painel, "O CPF do  digitador deve ser preenchido.", "Erro",
                    JOptionPane.ERROR_MESSAGE);
        } else if (endereco.length() > 75) {
            JOptionPane.showMessageDialog(painel, "O Endereço não pode ser maior que 75 caracteres.", "Aviso",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            return true;
        }

        return false;
    }

    private void jCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastrarActionPerformed
        // TODO add your handling code here:
        DigitadoresBanco db = new DigitadoresBanco();
        if (jCadastrar.getText().equals("Cadastrar")) {     //Se o nome for Cadastrar - Cadastra o Digitador
            if (checkCaixas(jPanel5, jNome, jNascimento, jSexoM, jSexoF, jRg, jCpf, jEndereco)) {
                //(id = -1) pois não há id ainda
                digitador = getFormatedDigitadores(-1, jNome, jNascimento, jSexoM, jContato, jRg, jCpf, jEndereco);
                if (db.validarCpfRg(digitador.getId(), digitador.getCpf(), digitador.getRg())) {

                    digitador.setLogin(digitador.getCpf());  //Ao cadastrar o login e senha do digitador serão seu cpf
                    digitador.setSenha(digitador.getCpf());
                    db = new DigitadoresBanco();
                    if (db.inserir(digitador)) {
                        JOptionPane.showMessageDialog(this, "O Digitador foi cadastrado com sucesso!\n\nInforme ao "
                                + "Digitador que seu Login e Senha são o CPF");
                        jNome.setText("");
                        jNascimento.setText("");
                        jSexoM.setSelected(false);
                        jSexoF.setSelected(false);
                        jContato.setText("");
                        jRg.setText("");
                        jCpf.setText("");
                        jEndereco.setText("");
                    } else {
                        JOptionPane.showMessageDialog(this, "Erro ao cadastrar o Digitador. Tente novamente.", "Erro",
                                JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Os dados informados no Cpf ou Rg já existem.", "Aviso",
                            JOptionPane.WARNING_MESSAGE);
                }
            }
        } else {                //Caso não se torna botão Editar - some ao ser apertado
            jCadastrar.setVisible(false);
            jAtualizar.setVisible(true);
            jPin.setVisible(true);
            jNomePin.setVisible(true);

            if (!("Admin").equals(jNome.getText())) {  // O nome do Admin não pode ser modificado
                jNome.setEnabled(true);
            }
            jNascimento.setEnabled(true);
            jSexoM.setEnabled(true);
            jSexoF.setEnabled(true);
            jContato.setEnabled(true);
            jRg.setEnabled(true);
            jCpf.setEnabled(true);
            jEndereco.setEnabled(true);
        }
    }//GEN-LAST:event_jCadastrarActionPerformed

    private void jAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAtualizarActionPerformed
        // TODO add your handling code here:
        DigitadoresBanco db = new DigitadoresBanco();
        int escolha;

        //Ao apertar o botao editar este botao atualizar aparece. Apertando este
        //botão, se tudo tiver certo, aparecerá uma mensagem de confirmação e
        //após ocorrerá validação do pin colocado
        if (checkCaixas(jPanel5, jNome, jNascimento, jSexoM, jSexoF, jRg, jCpf, jEndereco)) {
            escolha = JOptionPane.showConfirmDialog(null, "Deseja realmente modificar os seus dados?",
                    "Modificar dados", 0, JOptionPane.QUESTION_MESSAGE);

            if (escolha == 0) {  // confirmação do usuario
                if (digitador.getPin().equals(new String(jPin.getPassword()))) {
                    digitador = getFormatedDigitadores(idDigit, jNome, jNascimento, jSexoM, jContato, jRg, jCpf, jEndereco);

                    if (db.validarCpfRg(digitador.getId(), digitador.getCpf(), digitador.getRg())) {
                        db = new DigitadoresBanco();
                        if (db.atualizar(digitador)) {
                            JOptionPane.showMessageDialog(this, "Atualizado com sucesso!\n\nSe modificou o seu Nome, ele aparecerá na aba Conta no seu próximo Acesso.");
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(this, "Erro ao atualizar os seus dados. Tente novamente.", "Erro",
                                    JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Os dados informados no Cpf ou Rg já existem.", "Erro",
                                JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Pin Incorreto. Tente novamente.", "Erro",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jAtualizarActionPerformed

    private void jNascimentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNascimentoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jNascimentoKeyReleased

    private void jNascimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNascimentoKeyPressed
        // TODO add your handling code here:
        TelaCadCadastrar.apagarJFormatted(jNascimento, evt.getKeyCode());
    }//GEN-LAST:event_jNascimentoKeyPressed

    private void jContatoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jContatoKeyPressed
        // TODO add your handling code here:
       TelaCadCadastrar.apagarJFormatted(jContato, evt.getKeyCode());
    }//GEN-LAST:event_jContatoKeyPressed

    private void jCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCpfKeyPressed
        // TODO add your handling code here:
        TelaCadCadastrar.apagarJFormatted(jCpf, evt.getKeyCode());
    }//GEN-LAST:event_jCpfKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAtualizar;
    private javax.swing.JButton jCadastrar;
    private javax.swing.JFormattedTextField jContato;
    private javax.swing.JFormattedTextField jCpf;
    private javax.swing.JTextField jEndereco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField jNascimento;
    private javax.swing.JTextField jNome;
    private javax.swing.JLabel jNomePin;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField jPin;
    private javax.swing.JTextField jRg;
    private javax.swing.JCheckBox jSexoF;
    private javax.swing.JCheckBox jSexoM;
    // End of variables declaration//GEN-END:variables

}
