/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualizar;

import modelos.Digitadores;
import modelos.banco.DigitadoresBanco;

/**
 *
 * @author renan
 */
public class TelaInicial extends javax.swing.JFrame {

    private int digiUsoId;
    private boolean check;
    private Digitadores digitador;

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        jMenuDigitadores.setVisible(false);
    }

    public TelaInicial(int id) {
        initComponents();
        this.digiUsoId = id;

        jMenuDigitadores.setVisible(false);
    }

    public TelaInicial(int id, boolean check) {
        initComponents();
        this.digiUsoId = id;
        this.check = check;

        jMenuDigitadores.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jUser = new javax.swing.JMenu();
        jUserInfo = new javax.swing.JMenuItem();
        jAlterarSenha = new javax.swing.JMenuItem();
        jSair = new javax.swing.JMenuItem();
        jMenuDigitadores = new javax.swing.JMenu();
        jdCadastrar = new javax.swing.JMenuItem();
        jdProcurar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jcCadastrar = new javax.swing.JMenuItem();
        jcProcurar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SCOH");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons-hosp.png")).getImage());
        setPreferredSize(new java.awt.Dimension(900, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-gerente-16.png"))); // NOI18N
        jUser.setText("Conta");
        jUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserActionPerformed(evt);
            }
        });

        jUserInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-nome-16.png"))); // NOI18N
        jUserInfo.setText("Sua Conta");
        jUserInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserInfoActionPerformed(evt);
            }
        });
        jUser.add(jUserInfo);

        jAlterarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-macho-de-configurações-de-admin-16.png"))); // NOI18N
        jAlterarSenha.setText("Alterar Senha");
        jAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlterarSenhaActionPerformed(evt);
            }
        });
        jUser.add(jAlterarSenha);

        jSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/door_out.png"))); // NOI18N
        jSair.setText("Sair");
        jSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairActionPerformed(evt);
            }
        });
        jUser.add(jSair);

        jMenuBar1.add(jUser);

        jMenuDigitadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-pessoa-do-sexo-masculino-16.png"))); // NOI18N
        jMenuDigitadores.setText("Digitadores");
        jMenuDigitadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDigitadoresActionPerformed(evt);
            }
        });

        jdCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-adicionar-administrador-16.png"))); // NOI18N
        jdCadastrar.setText("Cadastrar");
        jdCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdCadastrarActionPerformed(evt);
            }
        });
        jMenuDigitadores.add(jdCadastrar);

        jdProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-homem-escritor-16.png"))); // NOI18N
        jdProcurar.setText("Procurar/Editar");
        jdProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdProcurarActionPerformed(evt);
            }
        });
        jMenuDigitadores.add(jdProcurar);

        jMenuBar1.add(jMenuDigitadores);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group.png"))); // NOI18N
        jMenu2.setText("Cadastros");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jcCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group_add.png"))); // NOI18N
        jcCadastrar.setText("Cadastrar");
        jcCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCadastrarActionPerformed(evt);
            }
        });
        jMenu2.add(jcCadastrar);

        jcProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group_edit.png"))); // NOI18N
        jcProcurar.setText("Procurar/Editar");
        jcProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcProcurarActionPerformed(evt);
            }
        });
        jMenu2.add(jcProcurar);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-sobre-16.png"))); // NOI18N
        jMenu3.setText("Sobre");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jcCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCadastrarActionPerformed
        // TODO add your handling code here:
        TelaCadCadastrar tc = new TelaCadCadastrar(digiUsoId);
        jDesktopPane1.add(tc).setVisible(true);
    }//GEN-LAST:event_jcCadastrarActionPerformed

    private void jdCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdCadastrarActionPerformed
        // TODO add your handling code here:
        TelaDigitCadastrar tdc = new TelaDigitCadastrar();
        jDesktopPane1.add(tdc).setVisible(true);
    }//GEN-LAST:event_jdCadastrarActionPerformed

    private void jMenuDigitadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDigitadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuDigitadoresActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jcProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcProcurarActionPerformed
        // TODO add your handling code here:
        TelaCadProcurar tcp = new TelaCadProcurar(digitador); //teste
        jDesktopPane1.add(tcp).setVisible(true);
    }//GEN-LAST:event_jcProcurarActionPerformed
    /**
     *passando para o atual digitador uma lista que contém os seus dados
     * @return 
     */
    private Digitadores getFormattedDigitadores(){
        DigitadoresBanco db = new DigitadoresBanco();
        Digitadores digi = new Digitadores();
        String newNasc;
        for (Digitadores d : db.procurarEspecificoDigit(digiUsoId)) {  
            digi.setId(digiUsoId);
            digi.setNome(d.getNome());
            newNasc = d.getNascimento(); // ajeita a data que vem do banco
            digi.setNascimento(newNasc.substring(8, 10) + newNasc.substring(5, 7) + newNasc.substring(0, 4)); 
            digi.setSexo(d.getSexo());
            digi.setRg(d.getRg());
            digi.setCpf(d.getCpf());
            digi.setContato(d.getContato());
            digi.setEndereco(d.getEndereco());
            digi.setLogin(d.getLogin());
            digi.setSenha(d.getSenha());
            digi.setPin(d.getPin());
        }
        return digi;
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        digitador = getFormattedDigitadores();
        jUserInfo.setText(digitador.getNome());
        
        if (digitador.getNome().equals("Admin") || digitador.getNome().equals("")) {
            jMenuDigitadores.setVisible(true);
        }

        if (check) {   //alterar login/senha (1º login)
            new TelaAtualizarAdmin(digiUsoId).setVisible(true);
        } else{
            if (digitador.getCpf().equals(digitador.getLogin()) && digitador.getCpf().equals(digitador.getSenha())){
                boolean alterar = false;
                new TelaAtualizarAdmin(digiUsoId, alterar).setVisible(true);
            }
        } 
    }//GEN-LAST:event_formWindowOpened

    private void jSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairActionPerformed
        // TODO add your handling code here:
        new TelaLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jSairActionPerformed

    private void jAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlterarSenhaActionPerformed
        // TODO add your handling code here:
        boolean alterar = true;
        new TelaAtualizarAdmin(digiUsoId, alterar).setVisible(true);
    }//GEN-LAST:event_jAlterarSenhaActionPerformed

    private void jUserInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserInfoActionPerformed
        // TODO add your handling code here:
        digitador = getFormattedDigitadores();        

        TelaDigitCadastrar tdc = new TelaDigitCadastrar(digitador);
        jDesktopPane1.add(tdc).setVisible(true);
    }//GEN-LAST:event_jUserInfoActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUserActionPerformed

    private void jdProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdProcurarActionPerformed
        // TODO add your handling code here:
        TelaDigitProcurar tdp = new TelaDigitProcurar(digitador);
        jDesktopPane1.add(tdp).setVisible(true);
    }//GEN-LAST:event_jdProcurarActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        new TelaSobre(this, true).setVisible(true); //jdialog
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAlterarSenha;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDigitadores;
    private javax.swing.JMenuItem jSair;
    private javax.swing.JMenu jUser;
    private javax.swing.JMenuItem jUserInfo;
    private javax.swing.JMenuItem jcCadastrar;
    private javax.swing.JMenuItem jcProcurar;
    private javax.swing.JMenuItem jdCadastrar;
    private javax.swing.JMenuItem jdProcurar;
    // End of variables declaration//GEN-END:variables
}
