/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualizar;

import com.sun.glass.events.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;
import modelos.Digitadores;
import modelos.banco.DigitadoresBanco;

/**
 *
 * @author renan
 */
public class TelaVisualDigit extends javax.swing.JInternalFrame {

    private Digitadores digitador;

    /**
     * Creates new form TelaUserInfo
     */
    public TelaVisualDigit() {
        initComponents();
    }

    public TelaVisualDigit(Digitadores digi, boolean alterar) {
        initComponents();
        this.digitador = digi;

        setTitle("Digitador: " + digi.getNome());
        
        Border linBorda = jPanel5.getBorder();
        TitledBorder titBorda;
        if (alterar) {
            titBorda = BorderFactory.createTitledBorder(linBorda, "Atualizar Digitador");
        } else {
            titBorda = BorderFactory.createTitledBorder(linBorda, "Visualizar Digitador");
        }
        jPanel5.setBorder(titBorda);

        jNome.setText(digi.getNome());
        jNascimento.setText(digi.getNascimento());

        if (digi.getSexo().equals("M")) {
            jSexoM.setSelected(true);
        } else if (digi.getSexo().equals("F")) {
            jSexoF.setSelected(true);
        }
        jContato.setText(digi.getContato());
        jRg.setText(digi.getRg());
        jCpf.setText(digi.getCpf());
        jEndereco.setText(digi.getEndereco());

        if (alterar) {
            jProcurarCad.setVisible(false);
        } else {
            jNome.setEnabled(false);
            jNascimento.setEnabled(false);
            jSexoM.setEnabled(false);
            jSexoF.setEnabled(false);
            jContato.setEnabled(false);
            jRg.setEnabled(false);
            jCpf.setEnabled(false);
            jEndereco.setEnabled(false);
            jAtualizar.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jNome = new javax.swing.JTextField();
        jNascimento = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jSexoM = new javax.swing.JCheckBox();
        jSexoF = new javax.swing.JCheckBox();
        jContato = new javax.swing.JFormattedTextField();
        jAtualizar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCpf = new javax.swing.JFormattedTextField();
        jEndereco = new javax.swing.JTextField();
        jRg = new javax.swing.JTextField();
        jProcurarCad = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Digitador");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Nome*");

        jLabel2.setText("Nascimento*");

        jLabel3.setText("Contato");

        try {
            jNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jNascimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNascimentoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jNascimentoKeyReleased(evt);
            }
        });

        jLabel4.setText("Sexo*");

        jSexoM.setText("M");
        jSexoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSexoMActionPerformed(evt);
            }
        });

        jSexoF.setText("F");
        jSexoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSexoFActionPerformed(evt);
            }
        });

        try {
            jContato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jContato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jContatoKeyPressed(evt);
            }
        });

        jAtualizar.setText("Atualizar");
        jAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAtualizarActionPerformed(evt);
            }
        });

        jLabel9.setText("RG*");

        jLabel10.setText("CPF*");

        jLabel11.setText("Endereço");

        try {
            jCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCpfKeyPressed(evt);
            }
        });

        jEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEnderecoActionPerformed(evt);
            }
        });
        jEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jEnderecoKeyPressed(evt);
            }
        });

        jProcurarCad.setText("Procurar Cadastros");
        jProcurarCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProcurarCadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(jRg, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProcurarCad))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addComponent(jLabel4)
                                                .addGap(55, 55, 55)
                                                .addComponent(jLabel3)
                                                .addGap(109, 109, 109))
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(jSexoM)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jSexoF)
                                                .addGap(18, 18, 18)
                                                .addComponent(jContato, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addComponent(jLabel11))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jAtualizar)
                        .addGap(81, 81, 81))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSexoM)
                    .addComponent(jSexoF)
                    .addComponent(jContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAtualizar)
                    .addComponent(jProcurarCad))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSexoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSexoMActionPerformed
        // TODO add your handling code here:
        if (jSexoF.isSelected()) {
            jSexoF.setSelected(false);
        }
    }//GEN-LAST:event_jSexoMActionPerformed

    private void jSexoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSexoFActionPerformed
        // TODO add your handling code here:
        if (jSexoM.isSelected()) {
            jSexoM.setSelected(false);
        }
    }//GEN-LAST:event_jSexoFActionPerformed

    /**
     * Se confirmado atualiza os dados do digitador
     */
    private void atualizarDigitador() {
        DigitadoresBanco db = new DigitadoresBanco();
        int escolha;

        if (TelaDigitCadastrar.checkCaixas(jPanel5, jNome, jNascimento, jSexoM, jSexoF, jRg, jCpf, jEndereco)) {
            escolha = JOptionPane.showConfirmDialog(this, "Deseja realmente modificar os dados do digitador?",
                    "Modificar dados", 0, JOptionPane.QUESTION_MESSAGE);

            if (escolha == 0) {  // confirmação do usuario
                digitador = TelaDigitCadastrar.getFormatedDigitadores(digitador.getId(), jNome, jNascimento, jSexoM,
                        jContato, jRg, jCpf, jEndereco);

                if (db.validarCpfRg(digitador.getId(), digitador.getCpf(), digitador.getRg())) {
                    db = new DigitadoresBanco();
                    if (db.atualizar(digitador)) {
                        JOptionPane.showMessageDialog(this, "Digitador atualizado com sucesso.");
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Erro ao atualizar os dados do digitador. Tente novamente.", "Erro",
                                JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Os dados informados no Cpf ou Rg já existem.", "Erro",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }

    private void jAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAtualizarActionPerformed
        // TODO add your handling code here:
        atualizarDigitador();
    }//GEN-LAST:event_jAtualizarActionPerformed

    private void jNascimentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNascimentoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jNascimentoKeyReleased

    private void jNascimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNascimentoKeyPressed
        // TODO add your handling code here:
        TelaCadCadastrar.apagarJFormatted(jNascimento, evt.getKeyCode());
    }//GEN-LAST:event_jNascimentoKeyPressed

    private void jProcurarCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProcurarCadActionPerformed
        // TODO add your handling code here:        
        TelaCadProcurar tcp = new TelaCadProcurar(digitador);
        getParent().add(tcp).setVisible(true);
    }//GEN-LAST:event_jProcurarCadActionPerformed

    private void jEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEnderecoActionPerformed

    private void jCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCpfKeyPressed
        // TODO add your handling code here:
        TelaCadCadastrar.apagarJFormatted(jCpf, evt.getKeyCode());
    }//GEN-LAST:event_jCpfKeyPressed

    private void jContatoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jContatoKeyPressed
        // TODO add your handling code here:
        TelaCadCadastrar.apagarJFormatted(jContato, evt.getKeyCode());
    }//GEN-LAST:event_jContatoKeyPressed

    private void jEnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEnderecoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            atualizarDigitador();
        }
    }//GEN-LAST:event_jEnderecoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAtualizar;
    private javax.swing.JFormattedTextField jContato;
    private javax.swing.JFormattedTextField jCpf;
    private javax.swing.JTextField jEndereco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField jNascimento;
    private javax.swing.JTextField jNome;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jProcurarCad;
    private javax.swing.JTextField jRg;
    private javax.swing.JCheckBox jSexoF;
    private javax.swing.JCheckBox jSexoM;
    // End of variables declaration//GEN-END:variables

}
